print("sinh viên: Nguyễn Quang Hải")
print("MSSV: 235752021610099")
input_string = input("Nhập vào một xâu ký tự: ")
words = input_string.split()
print("Danh sách các từ sau khi tách:")
print(words)
joined_string = ' '.join(words)
print("Xâu ký tự sau khi nối lại:")
print(joined_string)